### PR TITLE
fix padding on menu item and grey to gray

### LINKED ISSUE #29: Fix location menu item UI
Fix spacing inconsistencies with figma (spacing from left of icon, etc.)
Icon needs to be different between apple place and bus stop

### PR DESCRIPTION
**Pull request by 04jono**
* Renamed "grey" constants to "gray"
* Fix padding on menu item for searches, also changed icon based on place type (bus stop or other apple place)

Screenshot:

Screenshot from 2024-09-20 12-30-18

Figma:

image

Closes #29

### CODE REVIEW

File: app/src/main/java/com/cornellappdev/transit/ui/components/MenuItem.kt [hunk 1]
```diff
@@ -29,31 +29,45 @@ import com.cornellappdev.transit.ui.theme.sfProDisplayFamily
...
         Column() {
             Text(
                 text = label,
                 fontSize = 14.sp,
                 color = PrimaryText,
-                fontFamily = sfProDisplayFamily
+                fontFamily = sfProDisplayFamily,
+                maxLines = 1,
+                overflow = TextOverflow.Ellipsis,
+                lineHeight = 16.sp
```
Comment (thisjustin123) [inline app/src/main/java/com/cornellappdev/transit/ui/components/MenuItem.kt:61]: You remember the vertical spacing thing driving us literally insane? I found the solution buried super deep in a Medium article.

Apply this:

```
                style = TextStyle(
                    platformStyle = PlatformTextStyle(
                        includeFontPadding = false
                    )
                )
```
to each `Text()`. The result is text that is correctly NOT vertically padded:

image

hehe i already did it on my end but im making u do it now :-)

**Review by thisjustin123 — CHANGES_REQUESTED** [review]
vertical padding fix

**Review by thisjustin123 — APPROVED** [review]
Perrrfect, love the `Style` class.
