### PR TITLE
Fix flickering error issue

### LINKED ISSUE #75: Route error state flickers when switching routes on route options screen
https://github.com/user-attachments/assets/cdbdf4ca-cbb1-4303-b6f0-3482a4e2cb4e

### PR DESCRIPTION
**Pull request by 04jono**
## Overview

Fixes flickering error when swapping start and destination on Route screen.
## Changes Made

Presumed cause: when we swap start and destination, we change swap start to dest and then dest to start sequentially. In between this non-atomic swap, a call to backend is made which immediately fails, causing the error flicker.

Adding a debounce of 50ms before the HTTP request allows the swap to fully complete before we make a bad request.
## Related PRs or Issues (delete if not applicable)

Fixes #75 
## Screenshots (delete if not applicable)

[swap.webm](https://github.com/user-attachments/assets/6d23db69-404b-4e7c-82ef-1ba0c504bec0)

### CODE REVIEW

**Review by zachseidner1 — CHANGES_REQUESTED** [review]
I don't really like this fix. The problem shows a bigger architectural issue for `SelectedRouteRepository`. Instead of exposing multiple flows, we should expose a single flow that contains `SelectedRouteRepositoryState`, a `data class` that could have `startPlace` and `endPlace` as members. This way, we could create a `swapLocations` function that atomically updates the repository state so we wouldn't have this issue. Future implementors might forget why `debounce(50L)` is applied to this flow, and remove it because it doesn't make sense. We should try and address the root of the problem, and this refactor shouldn't take too long.

File: app/src/main/java/com/cornellappdev/transit/ui/viewmodels/RouteViewModel.kt [hunk 1]
```diff
@@ -159,27 +153,22 @@ class RouteViewModel @Inject constructor(
             }
         }.launchIn(viewModelScope)
 
-        combine(startPlace, destPlace, arriveByFlow) { start, dest, arriveBy ->
-            Triple(start, dest, arriveBy)
+        combine(selectedRoute, arriveByFlow) { startAndEnd, arriveBy ->
+            startAndEnd to arriveBy
         }.onEach {
```
Comment (zachseidner1) [inline app/src/main/java/com/cornellappdev/transit/ui/viewmodels/RouteViewModel.kt:158]: Nit: instead of combining into a pair and then calling `onEach`, you can just write your code directly in `combine`

File: app/src/main/java/com/cornellappdev/transit/ui/viewmodels/SelectedRouteState.kt
Comment (zachseidner1) [inline app/src/main/java/com/cornellappdev/transit/ui/viewmodels/SelectedRouteState.kt:1]: Nit: I prefer to have repository states declared right on top of their repositories.

**Review by zachseidner1 — APPROVED** [review]
Thanks for refactoring, nice job with this! Left a couple nits, but as always completely up to you.
