### PR TITLE
AddFavorites Search Bar Issue fixes

### LINKED ISSUE #72: Border around search box for Add Favorites is almost invisible
Image

### LINKED ISSUE #73: Information icon on favorites search bar does nothing
No functionality
Image

### PR DESCRIPTION
**Pull request by Mihilih**
## Overview

Added a border to the search bar and replaced the trailing icon.

## Changes Made

- Added a border to the add favorites search bar
- Removed the info icon at the end of the search bar
- Added a clear icon to the end of the search bar to clear the query

## Test Coverage

Samsung A14 physical emulator

## Related PRs or Issues (delete if not applicable)

Fixes #72 
Fixes #73 

## Screenshots (delete if not applicable)

<details>
  <summary>Add Favorites Search Sheet</summary>
  

WhatsApp Image 2025-02-26 at 5 42 54 PM

</details>

### CODE REVIEW

File: app/src/main/java/com/cornellappdev/transit/ui/components/AddFavoritesSearchSheet.kt [hunk 1]
```diff
@@ -128,8 +130,19 @@ fun AddFavoritesSearchSheet(
                     dividerColor = DividerGray,
                 ),
                 leadingIcon = { Icon(Icons.Outlined.Search, "Search") },
-                trailingIcon = { Icon(Icons.Outlined.Info, "Info") },
-                placeholder = { Text(text = "Search for a stop to add") }
+                trailingIcon = {
```
Comment (zachseidner1) [inline app/src/main/java/com/cornellappdev/transit/ui/components/AddFavoritesSearchSheet.kt:133]: This icon should only show if the text is not empty.

**Review by zachseidner1 — COMMENTED** [review]
Very nice work, I just don't think we should be able to clear the search when the text is empty. Should be a 2 line fix.

**Review by zachseidner1 — APPROVED** [review]
Thank you! I think that one line fix makes the feature much nicer.
