### PR TITLE
Fix search and create initial Route Details screen

### LINKED ISSUE #16: Paint a route on the map
Given a route, paint it on the HomeScreen Google Map.

### LINKED ISSUE #23: Fix search
use applesearch endpoint

### PR DESCRIPTION
**Pull request by 04jono**
* Search is fixed, uses appleSearch endpoint now. Updated search flow logic for favorites bottom sheet and home screen search. Removed some dependencies on old way of iterating through list of stops.

* Low-fidelity Route Details screen, can display routes queried from backend. Below image is partially hardcoded (specific start and end chosen).

image

image

Closes #23 
Closes #16

### CODE REVIEW

File: app/src/main/java/com/cornellappdev/transit/models/Place.kt [hunk 1]
```diff
@@ -0,0 +1,35 @@
...
+data class QueryResult(
+    @Json(name = "applePlaces") var places : List<Place>,
+    @Json(name = "busStops") var stops : List<Place>
+)
+
+//TODO: Deprecated, start migrating to Place data class
+/**
+ * DEPRECATED: Data class representing a TCAT stop
+ */
+data class Stop(
```
Comment (thisjustin123) [inline app/src/main/java/com/cornellappdev/transit/models/Place.kt:19]: I think there's an `@deprecated` annotation for this?

File: app/src/main/java/com/cornellappdev/transit/ui/screens/DetailsScreen.kt [hunk 2]
```diff
@@ -0,0 +1,161 @@
...
+
+        Divider(thickness = 1.dp, color = DividerGrey)
+        GoogleMap(
+            modifier = Modifier.fillMaxSize(),
+            cameraPositionState = cameraPositionState,
+            properties = MapProperties(
+                isMyLocationEnabled = permissionState.status.isGranted
+            ),
+            uiSettings = MapUiSettings(zoomControlsEnabled = false)
+        ) {
```
Comment (thisjustin123) [inline app/src/main/java/com/cornellappdev/transit/ui/screens/DetailsScreen.kt:109]: To make this composable more readable and a bit less jumbled with everything in one function, let's split the map function and everything in it into its own `private fun`. Take a look at how I (generally) split `HomeScreen.kt` on [this eatery PR.](https://github.com/cuappdev/eatery-blue-android/pull/143)

Feel free to ask for clarification

File: app/src/main/java/com/cornellappdev/transit/ui/screens/HomeScreen.kt [hunk 3]
```diff
@@ -125,10 +128,7 @@ fun HomeScreen(
     // Search bar flow
     val searchBarValue = homeViewModel.searchQuery.collectAsState().value
 
-    // Collect flow of rides through API
-    val stopsApiResponse = homeViewModel.stopFlow.collectAsState().value
-    val queryResponse = homeViewModel.queryFlow.collectAsState().value
-    val placesResponse = homeViewModel.placeData.collectAsState().value
+    val placeQueryResponse = homeViewModel.placeQueryFlow.collectAsState().value
```
Comment (thisjustin123) [inline app/src/main/java/com/cornellappdev/transit/ui/screens/HomeScreen.kt:131]: For the future, I'll have any files that have a ton of flows use some internal `ViewState` class to package all the flow values together with `.copy()` calls. It's better practice. But that's for a later PR i suppose.

**Review by thisjustin123 — CHANGES_REQUESTED** [review]
Plz refactor the detail screen class to improve readability! Otherwise actually very neat code :D

I'll try to go over some best practices notions though next SM to improve some of the `ViewModels` here. But no need to worry about that now.

File: app/src/main/java/com/cornellappdev/transit/ui/screens/HomeScreen.kt (hunk 3 above)
Comment (04jono) [reply app/src/main/java/com/cornellappdev/transit/ui/screens/HomeScreen.kt:131]: Noted

File: app/src/main/java/com/cornellappdev/transit/models/Place.kt [hunk 4]
```diff
@@ -12,24 +13,22 @@ data class QueryResult(
...
  */
-data class Stop(
-    @Json(name = "lat") var latitude: Double,
-    @Json(name = "long") var longitude: Double,
-    @Json(name = "name") var name: String,
-    @Json(name = "type") var type: String,
-)
+enum class Type() {
+    busStop,
+    applePlace
```
Comment (thisjustin123) [inline app/src/main/java/com/cornellappdev/transit/models/Place.kt:21]: plz name any enums as `BUS_STOP` convention :)

File: app/src/main/java/com/cornellappdev/transit/models/Place.kt [hunk 5]
```diff
@@ -12,24 +13,22 @@ data class QueryResult(
...
- * DEPRECATED: Data class representing a TCAT stop
+ * Enum class representing the types of TCAT places
  */
-data class Stop(
-    @Json(name = "lat") var latitude: Double,
-    @Json(name = "long") var longitude: Double,
-    @Json(name = "name") var name: String,
-    @Json(name = "type") var type: String,
-)
+enum class Type() {
```
Comment (thisjustin123) [inline app/src/main/java/com/cornellappdev/transit/models/Place.kt:19]: Any reason for `()` here?

Comment (thisjustin123) [reply app/src/main/java/com/cornellappdev/transit/models/Place.kt:19]: Also, the name `Type` is a little generic. Maybe something like `PlaceType`?

**Review by thisjustin123 — CHANGES_REQUESTED** [review]
A few more things! Thanks for refactoring the detail screen :-)

File: app/src/main/java/com/cornellappdev/transit/models/Place.kt (hunk 5 above)
Comment (Mihilih) [reply app/src/main/java/com/cornellappdev/transit/models/Place.kt:19]: Lol these were changes on my branch so I'll fix them.

Comment (Mihilih) [reply app/src/main/java/com/cornellappdev/transit/models/Place.kt:19]: no reason for `()` and will change name to `PlaceType`.

File: app/src/main/java/com/cornellappdev/transit/models/Place.kt (hunk 4 above)
Comment (Mihilih) [reply app/src/main/java/com/cornellappdev/transit/models/Place.kt:21]: I did it like this because in the response from the backend, the possible values for the `type` field are these. If I have to change it to the `BUS_STOP` convention I think I should be adding a type adapter to Moshi (?). Is that alright?

File: app/src/main/java/com/cornellappdev/transit/models/Place.kt (hunk 5 above)
Comment (04jono) [reply app/src/main/java/com/cornellappdev/transit/models/Place.kt:19]: No worries @Mihilih ill fix them on this branch lol

File: app/src/main/java/com/cornellappdev/transit/ui/components/AddFavoritesSearchSheet.kt [hunk 6]
```diff
@@ -142,7 +142,7 @@ fun AddFavoritesSearchSheet(
                                 MenuItem(
                                     Icons.Filled.Place,
                                     label = it.name,
-                                    sublabel = if (it.type == Type.busStop) "Bus Stop" else it.detail.toString(),
+                                    sublabel = if (it.type == PlaceType.BUS_STOP) "Bus Stop" else it.detail.toString(),
```
Comment (thisjustin123) [inline app/src/main/java/com/cornellappdev/transit/ui/components/AddFavoritesSearchSheet.kt:145]: Sorry to keep adding comments! But this seems like a line of code you're repeating a lot: `it.type == PlaceType.BUS_STOP) "Bus Stop" else it.detail.toString()`

It sounds to me like this is an actual property of a Place! Perhaps you'd want this as a property called `sublabel`. But this isn't something that backend supplies; it's something that you compute from the data class parameters exclusively... sounds like you should make a constant property!

```kotlin
/**
 * Data class representing an apple place or a TCAT stop
 */
@Serializable
data class Place(
    @Json(name = "lat") var latitude: Double,
    @Json(name = "long") var longitude: Double,
    @Json(name = "name") var name: String,
    @Json(name = "detail") val detail: String?,
    @Json(name = "type") var type: PlaceType
) {

   // NEW CODE!
   val subLabel = if (type == PlaceType.BUS_STOP) "Bus Stop" else detail.toString()
}
```

(That should work...)

Now, everywhere you need a bus stop's sublabel, you just reference this property! And no longer do you have to look back and think--how's that computed again?

Comment (thisjustin123) [reply app/src/main/java/com/cornellappdev/transit/ui/components/AddFavoritesSearchSheet.kt:145]: (Plz replace prev occurrences! And if you want to call it something else be my guest! The main idea is to make this constant field thingy, whatever you wanna call it.)

Comment (thisjustin123) [reply app/src/main/java/com/cornellappdev/transit/ui/components/AddFavoritesSearchSheet.kt:145]: Also, just for safety, you might want to use the following syntax instead (it's somethign like this):

```
val subLabel
    get() = if (type == PlaceType.BUS_STOP) "Bus Stop" else detail.toString()
```

Because some of your fields aren't constant; this will recompute the sublabel on demand whenever it's queried for instead of computing it once and storing it forever. The original runs the risk of the sublabel still saying bus stop even if you mutate `type` to an `APPLE_PLACE`.

**Review by thisjustin123 — CHANGES_REQUESTED** [review]
One last thing, ping me when you've done this and ill quickly approve :-)

**Review by thisjustin123 — APPROVED** [review]
bomb has been defused 💣
